Fix Helm chart lint error
$ helm lint charts/rancher-supportability-review-crd/1.0.0/
==> Linting charts/rancher-supportability-review-crd/1.0.0/
[ERROR] Chart.yaml: chart type is not valid in apiVersion 'v1'. It is valid in apiVersion 'v2'
[INFO] values.yaml: file does not exist

Error: 1 chart(s) linted, 1 chart(s) failed

Signed-off-by: Masashi Honma <masashi.honma@gmail.com>